# Generated by Django 5.0.6 on 2026-06-20 02:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpdesk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('key', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z][A-Z0-9]{1,4}$', 'Key must be 2–5 uppercase letters/digits (it prefixes ticket numbers).')])),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(default='#6366f1', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_itsm_helpdesks', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HelpdeskMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('role_in_helpdesk', models.CharField(choices=[('member', 'Member'), ('lead', 'Lead')], default='member', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('helpdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='itsm_helpdesks.helpdesk')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsm_helpdesk_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='helpdesk',
            index=models.Index(fields=['key'], name='itsm_helpde_key_aa8556_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdesk',
            index=models.Index(fields=['status'], name='itsm_helpde_status_43ac76_idx'),
        ),
        migrations.AddIndex(
            model_name='helpdeskmembership',
            index=models.Index(fields=['helpdesk', 'is_active'], name='itsm_helpde_helpdes_cd23c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='helpdeskmembership',
            constraint=models.UniqueConstraint(fields=('helpdesk', 'user'), name='uniq_helpdesk_user'),
        ),
    ]
