# Generated by Django 5.0.6 on 2026-06-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='note_heading',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='transition',
            name='note_prompt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transition',
            name='note_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transition',
            name='note_visibility',
            field=models.CharField(choices=[('public', 'Public Comment'), ('private', 'Internal Note')], default='public', max_length=10),
        ),
    ]
