# Generated by Django 5.1.15 on 2026-06-25 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_scope(apps, schema_editor):
    """Map the legacy is_shared flag onto the new scope dimension: shared notes
    become Workspace (the AddField default), private notes become Personal."""
    CannedNote = apps.get_model("itsm_tickets", "CannedNote")
    CannedNote.objects.filter(is_shared=False).update(scope="personal")
    CannedNote.objects.filter(is_shared=True).update(scope="workspace")


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_helpdesks', '0002_helpdesk_order'),
        ('itsm_projects', '0007_backfill_project_memberships'),
        ('itsm_tickets', '0003_comment_attachment_ticket_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cannednote',
            name='helpdesk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_helpdesks.helpdesk'),
        ),
        migrations.AddField(
            model_name='cannednote',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_projects.project'),
        ),
        migrations.AddField(
            model_name='cannednote',
            name='scope',
            field=models.CharField(choices=[('personal', 'Personal'), ('workspace', 'Workspace'), ('project', 'Project')], db_index=True, default='workspace', max_length=12),
        ),
        migrations.AddIndex(
            model_name='cannednote',
            index=models.Index(fields=['scope'], name='itsm_ticket_scope_09c54d_idx'),
        ),
        migrations.RunPython(backfill_scope, migrations.RunPython.noop),
    ]
