# Generated by Django 5.0.6 on 2026-07-02 02:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_groups', '0002_initial'),
        ('itsm_projects', '0008_project_priority_matrix'),
        ('itsm_tickets', '0004_cannednote_scope'),
        ('itsm_workflows', '0003_transition_portal_allowed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='business_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='major_incident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_code',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('workaround', 'Workaround'), ('duplicate', 'Duplicate'), ('user_error', 'User Error')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_downtime',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='users_affected',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workaround_provided',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['project', 'major_incident'], name='itsm_ticket_project_73a34a_idx'),
        ),
    ]
