# Generated by Django 5.1.15 on 2026-06-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_projects', '0002_project_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='queue_columns',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
