# Generated by Django 5.1.15 on 2026-06-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_projects', '0003_project_queue_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_view_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='disabled_view_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
