# Generated by Django 5.0.6 on 2026-07-02 02:15

import apps.itsm_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_projects', '0007_backfill_project_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_matrix',
            field=models.JSONField(blank=True, default=apps.itsm_projects.models.default_priority_matrix),
        ),
    ]
