# Generated by Django 5.0.6 on 2026-06-20 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_groups', '0002_initial'),
        ('itsm_helpdesks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='helpdesk',
            field=models.ForeignKey(blank=True, help_text='Owning helpdesk; null = shared/global group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='itsm_helpdesks.helpdesk'),
        ),
    ]
