# Generated by Django 5.1.15 on 2026-06-30 11:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_rbac', '0005_sso_login_ticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('attr_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('multiselect', 'Multi-select')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('show_in_table', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAttributeOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=150)),
                ('color', models.CharField(blank=True, default='', max_length=16)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='itsm_rbac.userattributedefinition')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='itsm_rbac.userattributedefinition')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itsm_attribute_values', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userattributedefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('key',), name='uniq_user_attr_key'),
        ),
        migrations.AddConstraint(
            model_name='userattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='uniq_user_attr_option_value'),
        ),
        migrations.AddIndex(
            model_name='userattributevalue',
            index=models.Index(fields=['attribute'], name='itsm_rbac_u_attribu_6573cf_idx'),
        ),
        migrations.AddIndex(
            model_name='userattributevalue',
            index=models.Index(fields=['user'], name='itsm_rbac_u_user_id_5bc3d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='userattributevalue',
            constraint=models.UniqueConstraint(fields=('user', 'attribute'), name='uniq_user_attribute'),
        ),
    ]
