# Generated by Django 5.1.15 on 2026-06-22 01:50

import apps.itsm_email.crypto
import apps.itsm_email.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsm_groups', '0002_initial'),
        ('itsm_projects', '0003_project_queue_columns'),
        ('itsm_tickets', '0002_ticket_updated_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.EmailField(help_text='The catch address, e.g. support@company.com', max_length=254)),
                ('domain', models.CharField(blank=True, default='', help_text='Host used in Message‑ID / plus‑addressed Reply‑To (defaults to the address domain).', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('protocol', models.CharField(choices=[('imap', 'IMAP'), ('pop3', 'POP3')], default='imap', max_length=8)),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=993)),
                ('use_ssl', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('folder', models.CharField(default='INBOX', max_length=120)),
                ('auth_method', models.CharField(choices=[('basic', 'Username & password'), ('oauth_google', 'Google (OAuth2)'), ('oauth_microsoft', 'Microsoft 365 (OAuth2)')], default='basic', max_length=20)),
                ('password_enc', apps.itsm_email.crypto.EncryptedField(blank=True, default='')),
                ('oauth_access_token_enc', apps.itsm_email.crypto.EncryptedField(blank=True, default='')),
                ('oauth_refresh_token_enc', apps.itsm_email.crypto.EncryptedField(blank=True, default='')),
                ('oauth_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('oauth_authorized', models.BooleanField(default=False)),
                ('outbound_enabled', models.BooleanField(default=True, help_text='Send acknowledgement + agent‑reply mail FROM this mailbox.')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS'), ('none', 'None')], default='starttls', max_length=8)),
                ('smtp_username', models.CharField(blank=True, default='', help_text='Blank ⇒ reuse the inbound username.', max_length=255)),
                ('smtp_password_enc', apps.itsm_email.crypto.EncryptedField(blank=True, default='', help_text='Blank ⇒ reuse the inbound password (basic auth).')),
                ('smtp_from_name', models.CharField(blank=True, default='', help_text='Display name on the From header.', max_length=150)),
                ('create_users', models.BooleanField(default=True, help_text='Create a (non‑login) requestor account for unknown senders.')),
                ('default_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('priority_map', models.JSONField(blank=True, default=apps.itsm_email.models._default_priority_map, help_text='Email priority signal (X-Priority/Importance/…) → ticket priority.')),
                ('strip_quotes', models.BooleanField(default=True)),
                ('cc_watchers', models.BooleanField(default=True)),
                ('reopen_policy', models.CharField(choices=[('comment_only', 'Comment only (leave closed)'), ('reopen', 'Reopen the ticket'), ('new_ticket', 'Create a new ticket')], default='comment_only', max_length=16)),
                ('reopen_window_days', models.PositiveIntegerField(default=14)),
                ('ignore_auto_replies', models.BooleanField(default=True)),
                ('max_age_days', models.PositiveIntegerField(default=7)),
                ('max_size_bytes', models.PositiveBigIntegerField(default=26214400, help_text='Whole‑message cap; larger mail is ignored (size_cap).')),
                ('max_attachment_bytes', models.PositiveBigIntegerField(default=10485760, help_text='Per‑attachment cap; larger parts are skipped (ticket is still created).')),
                ('loop_window_min', models.PositiveIntegerField(default=10)),
                ('loop_max_messages', models.PositiveIntegerField(default=30)),
                ('poll_interval_seconds', models.PositiveIntegerField(blank=True, help_text='Per‑channel override of the global poll cadence.', null=True)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_uid', models.PositiveBigIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('default_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_groups.group')),
                ('default_requestor', models.ForeignKey(blank=True, help_text='Used as requestor when create_users is off and the sender is unknown.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email_channels', to='itsm_projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('block', 'Block'), ('allow', 'Allow')], max_length=8)),
                ('pattern', models.CharField(help_text='Exact address or glob, e.g. *@spam.com', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('channel', models.ForeignKey(blank=True, help_text='Null = applies to all channels.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='itsm_email.emailchannel')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_type', 'pattern'],
            },
        ),
        migrations.CreateModel(
            name='EmailThreadMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(max_length=998)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_messages', to='itsm_email.emailchannel')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_tickets.comment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_messages', to='itsm_tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(max_length=998)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=998)),
                ('references', models.JSONField(blank=True, default=list)),
                ('from_addr', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=255)),
                ('to_addrs', models.JSONField(blank=True, default=list)),
                ('cc_addrs', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('date_header', models.DateTimeField(blank=True, null=True)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=10)),
                ('ignore_reason', models.CharField(blank=True, default='', max_length=40)),
                ('action_taken', models.CharField(blank=True, default='', max_length=40)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound', to='itsm_email.emailchannel')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_tickets.comment')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailchannel',
            index=models.Index(fields=['is_active'], name='itsm_email__is_acti_72741e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrule',
            index=models.Index(fields=['channel', 'rule_type'], name='itsm_email__channel_460793_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthreadmessage',
            index=models.Index(fields=['message_id'], name='itsm_email__message_59e3a1_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthreadmessage',
            index=models.Index(fields=['ticket'], name='itsm_email__ticket__3d0000_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailthreadmessage',
            constraint=models.UniqueConstraint(fields=('channel', 'message_id'), name='uniq_thread_channel_msgid'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['status', 'next_attempt_at'], name='itsm_email__status_fe1415_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['from_addr', 'created_at'], name='itsm_email__from_ad_9b0926_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundemail',
            index=models.Index(fields=['message_id'], name='itsm_email__message_6f609d_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundemail',
            constraint=models.UniqueConstraint(fields=('channel', 'message_id'), name='uniq_inbound_channel_msgid'),
        ),
    ]
