# Generated by Django 5.1.15 on 2026-06-25 15:17

import apps.itsm_email.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_email', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailchannel',
            name='oauth_client_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailchannel',
            name='oauth_client_secret_enc',
            field=apps.itsm_email.crypto.EncryptedField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emailchannel',
            name='oauth_tenant_id',
            field=models.CharField(blank=True, default='', help_text="Microsoft only: Directory (tenant) ID, or 'common'/'organizations'. Ignored for Google.", max_length=128),
        ),
    ]
