# Generated by Django 5.1.15 on 2026-06-17 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ticket_created', 'Ticket created'), ('field_changed', 'Field changed'), ('status_changed', 'Status changed'), ('assigned', 'Assignee changed'), ('group_changed', 'Group changed'), ('priority_changed', 'Priority changed'), ('comment_added', 'Comment added'), ('comment_edited', 'Comment edited'), ('comment_deleted', 'Comment deleted'), ('attachment_added', 'Attachment added'), ('attachment_removed', 'Attachment removed'), ('watcher_added', 'Watcher added'), ('watcher_removed', 'Watcher removed'), ('link_added', 'Ticket linked'), ('link_removed', 'Ticket link removed'), ('sla_started', 'SLA started'), ('sla_paused', 'SLA paused'), ('sla_resumed', 'SLA resumed'), ('sla_breached', 'SLA breached'), ('reopened', 'Ticket reopened'), ('closed', 'Ticket closed'), ('template_applied', 'Template applied')], max_length=32)),
                ('field_key', models.CharField(blank=True, default='', max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
