# Generated by Django 5.1.15 on 2026-06-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsm_core', '0001_initial'),
        ('itsm_tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='itsm_tickets.ticket'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ticket', '-created_at'], name='itsm_core_a_ticket__8ffe70_idx'),
        ),
    ]
