# Generated by Django 5.1.15 on 2026-06-20 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsm_core', '0001_initial'),
        ('itsm_projects', '0001_initial'),
        ('itsm_tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='itsm_tickets.ticket'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='itsm_projects.project'),
        ),
        migrations.AddField(
            model_name='fieldlayout',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldlayout',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_layouts', to='itsm_projects.project'),
        ),
        migrations.AddField(
            model_name='fieldlayout',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_layouts', to='itsm_projects.tickettype'),
        ),
        migrations.AddField(
            model_name='fieldlayoutitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldlayoutitem',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_items', to='itsm_core.fielddefinition'),
        ),
        migrations.AddField(
            model_name='fieldlayoutitem',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itsm_core.fieldlayout'),
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='itsm_core.fielddefinition'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='itsm_core.fielddefinition'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='itsm_tickets.ticket'),
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='value_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ticket', '-created_at'], name='itsm_core_a_ticket__8ffe70_idx'),
        ),
        migrations.AddIndex(
            model_name='fielddefinition',
            index=models.Index(fields=['project', 'field_type'], name='itsm_core_f_project_849f93_idx'),
        ),
        migrations.AddConstraint(
            model_name='fielddefinition',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='uniq_project_field_key'),
        ),
        migrations.AddConstraint(
            model_name='fieldlayout',
            constraint=models.UniqueConstraint(fields=('project', 'ticket_type'), name='uniq_project_type_layout'),
        ),
        migrations.AddConstraint(
            model_name='fieldlayoutitem',
            constraint=models.UniqueConstraint(fields=('layout', 'field'), name='uniq_layout_field'),
        ),
        migrations.AddConstraint(
            model_name='fieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='uniq_field_option_value'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['field'], name='itsm_core_f_field_i_7f6ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldvalue',
            index=models.Index(fields=['ticket'], name='itsm_core_f_ticket__25a52f_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldvalue',
            constraint=models.UniqueConstraint(fields=('ticket', 'field'), name='uniq_ticket_field'),
        ),
    ]
