# Generated by Django 5.0.6 on 2026-06-21 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldoption',
            name='level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fieldoption',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='itsm_core.fieldoption'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('multiline', 'Multi-line Text'), ('richtext', 'Rich Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'Date & Time'), ('dropdown', 'Dropdown'), ('multiselect', 'Multi-select'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('user_picker', 'User Picker'), ('group_picker', 'Group Picker'), ('cascade', 'Cascading (dependent)'), ('attachment', 'Attachment')], max_length=20),
        ),
    ]
