# Generated by Django 5.0.6 on 2026-06-21 05:08

from django.db import migrations, models

# Standard "other details" fields default to the right sidebar (one-time backfill for
# layouts created before regions existed). Everything else stays in the main column.
SIDEBAR_KEYS = ["priority", "mode", "requestor", "assigned_group", "assignee", "source"]


def set_initial_regions(apps, schema_editor):
    FieldLayoutItem = apps.get_model("itsm_core", "FieldLayoutItem")
    FieldLayoutItem.objects.filter(field__key__in=SIDEBAR_KEYS).update(region="sidebar")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_core', '0003_fieldoption_level_fieldoption_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldlayoutitem',
            name='region',
            field=models.CharField(choices=[('main', 'Main'), ('sidebar', 'Sidebar')], default='main', max_length=10),
        ),
        migrations.AddField(
            model_name='fieldlayoutitem',
            name='width',
            field=models.CharField(choices=[('full', 'Full'), ('half', 'Half')], default='full', max_length=8),
        ),
        migrations.RunPython(set_initial_regions, noop),
    ]
