# Generated by Django 5.1.15 on 2026-06-20 11:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsm_approvals', '0001_initial'),
        ('itsm_core', '0002_initial'),
        ('itsm_groups', '0002_initial'),
        ('itsm_helpdesks', '0001_initial'),
        ('itsm_projects', '0001_initial'),
        ('itsm_tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('color', models.CharField(default='#6366f1', max_length=16)),
                ('is_portal_visible', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('helpdesk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_categories', to='itsm_helpdesks.helpdesk')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='itsm_catalog.catalogcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('description_html', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=32)),
                ('requires_approval', models.BooleanField(default=False)),
                ('default_priority', models.CharField(default='medium', max_length=10)),
                ('summary_template', models.CharField(blank=True, max_length=500)),
                ('field_defaults', models.JSONField(blank=True, default=dict)),
                ('is_portal_visible', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('approval_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='itsm_approvals.approvalworkflow')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itsm_catalog.catalogcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('default_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_groups.group')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_items', to='itsm_projects.project')),
                ('request_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_core.fieldlayout')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='itsm_projects.tickettype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CatalogRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='itsm_catalog.catalogitem')),
                ('requestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_request', to='itsm_tickets.ticket')),
            ],
        ),
        migrations.AddIndex(
            model_name='catalogcategory',
            index=models.Index(fields=['helpdesk', 'sort_order'], name='itsm_catalo_helpdes_c572a8_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['category', 'sort_order'], name='itsm_catalo_categor_6bd7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['project', 'is_active'], name='itsm_catalo_project_32e459_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogitem',
            index=models.Index(fields=['is_portal_visible'], name='itsm_catalo_is_port_2232ca_idx'),
        ),
        migrations.AddIndex(
            model_name='catalogrequest',
            index=models.Index(fields=['item'], name='itsm_catalo_item_id_ebac88_idx'),
        ),
    ]
