# Generated by Django 5.1.15 on 2026-06-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm_approvals', '0001_initial'),
        ('itsm_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this approval policy applies to; null = helpdesk-wide / global.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_workflows', to='itsm_projects.project'),
        ),
    ]
